apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-03T06:01:19Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "189888"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 5b2b2895-fdff-11e9-9fa0-42010a8001b8
spec:
  clusterIP: 10.12.14.231
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31129
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
