apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: busybox
        command:
         - /bin/sh
         - -c
         - "sleep 3600;"
         - echo hello
         
        name: busybox
        resources: {}
      - image: busybox
        command:
         - /bin/sh
         - -c
         - "sleep 3600;"
         - echo hello
         
        name: busybox2
        resources: {}
status: {}
